#Configure the Server Port
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
   name: API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        #Route Mapping
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path= /expert/**
          filter:
            - RewritePath=/user(?<segment>/?.*), $\{segment}
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path= /innovator/**
          filter:
            - RewritePath=/user(?<segment>/?.*), $\{segment}

        - id: authentication-service
          uri: http://localhost:8089/
          predicates:
            - Path= /api/v1/**
          filter:
            - RewritePath=/useremail(?<segment>/?.*), $\{segment}

        - id: email-service
          uri: http://localhost:8085/
          predicates:
            - Path= /email/**
          filter:
            - RewritePath=/email(?<segment>/?.*), $\{segment}

        - id: poststorage-service
          uri: http://localhost:8091
          predicates:
            - Path= /innovation/**
          filter:
            - RewritePath=/post(?<segment>/?.*), $\{segment}
        - id: poststorage-service
          uri: http://localhost:8091
          predicates:
            - Path= /proposal/**
          filter:
            - RewritePath=/post(?<segment>/?.*), $\{segment}


